myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
#-*- coding:utf-8 -*-

from django.urls import path, re_path
from . import views

# namespace
app_name = 'tasks'

urlpatterns = [
    # Create a task
    path('create/', views.TaskCreateView.as_view(), name='task_create'),

    path('thanks/', views.thanks, name='task_thanks'),
    # Retrieve task list
    path('', views.TaskListView.as_view(), name='task_list'),
    # Retrieve single task object
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_detail'),
    # Update a task
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(), name='task_update'),
    # Delete a task
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='task_delete')


]

tasks/models.py
from django.db import models


# Create your models here.

# class Status(models.TextChoices):
#     UNSTARTED = 'u', "Not started yet"
#     ONGOING = 'o', "Ongoing"
#     FINISHED = 'f', "Finished"


# class Task(models.Model):
#     name = models.CharField(verbose_name="Task name", max_length=65, unique=True)
#     status = models.CharField(verbose_name="Task status", max_length=1, choices=Status.choices)


class Songs(models.TextChoices):
    A = 'Dildara', "Dildara"
    B = 'Perfect', "Perfect"
    C = 'Angel', "Angel"
    D = 'I need You', "I Need You"
    
class User_Request(models.Model):
    name = models.CharField(verbose_name="Name", max_length=500)
    contact = models.IntegerField(verbose_name="Phone", unique=True, primary_key=True)
    song = models.CharField(verbose_name="Song", max_length=100, choices=Songs.choices)

    def __str__(self):
        return self.name

tasks/forms.py
#-*- coding:utf-8 -*-
from .models import User_Request
from django import forms

class TaskForm(forms.ModelForm):
    class Meta:
        model = User_Request
        fields = "__all__"

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import User_Request
from .forms import TaskForm

from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView


def thanks(request):
    return render(request, 'tasks/user_request_thanks.html')

class TaskListView(ListView):
    model = User_Request
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = User_Request

class TaskCreateView(CreateView):
    model = User_Request
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_thanks')

class TaskUpdateView(UpdateView):
    model = User_Request
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskDeleteView(DeleteView):
    model = User_Request
    success_url = reverse_lazy('tasks:task_list')

tasks/templates/tasks/user_request_confirm_delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mike Kerr</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <div class="profile-card js-profile-card">
    <div class="profile-card__img">
      <img src="{% static 'Mike.jpeg' %}" alt="profile card">
    </div>

    <div class="profile-card__cnt js-profile-cnt">
      <div class="profile-card__name">Mike Kerr</div>
        
      <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete{{ task }}?</p>
        <input type="submit" value="Confirm" />
      </form>

      
  </div>
</div>
<script  src="{% static 'script.js' %}"></script>

</body>
</html>

tasks/templates/tasks/user_request_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Detail</title>
</head>
<body>
<p> Task Name: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Update</a> |
    <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
</p>
<p> Task Status: {{ task.get_status_display }} </p>
<p> <a href="{% url 'tasks:task_list' %}">View All Tasks</a> |
    <a href="{% url 'tasks:task_create'%}">New Task</a>
</p>
</body>
</html>

tasks/templates/tasks/user_request_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mike Kerr</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <div class="profile-card js-profile-card">
    <div class="profile-card__img">
      <img src="{% static 'Mike.jpeg' %}" alt="profile card">
    </div>

    <div class="profile-card__cnt js-profile-cnt">
      <div class="profile-card__name">Mike Kerr</div>
      <div class="profile-card__txt">Request A Song <strong>Here</strong></div>
        
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" class="btn btn-success" value="Submit"></p>
        </form>

      
  </div>
</div>
<script  src="{% static 'script.js' %}"></script>

</body>
</html>

tasks/templates/tasks/user_request_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mike Kerr</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">

<style>
.delete{
    color: red;
}
</style>

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <div class="profile-card js-profile-card">
    <div class="profile-card__img">
      <img src="{% static 'Mike.jpeg' %}" alt="profile card">
    </div>

    <div class="profile-card__cnt js-profile-cnt">
      <div class="profile-card__name">Mike Kerr</div>
      <div class="profile-card__txt">Requested Songs </div>

      <table class="table table-borderless">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Song</th>
            <th>Edit</th>
        </tr>
        <tr>{% for task in tasks %}
            <td>{{ forloop.counter }}</td>
            <td>{{ task.name }}</td>
            <td>{{ task.song }}</td>
            <td><a class="delete" href="{% url 'tasks:task_delete' task.contact %}">Delete</a></td>
        </tr>
        {% endfor %}
      </table>

  </div>
</div>
<script  src="{% static 'script.js' %}"></script>

</body>
</html>

tasks/templates/tasks/user_request_thanks.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mike Kerr</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <div class="profile-card js-profile-card">
    <div class="profile-card__img">
      <img src="{% static 'Mike.jpeg' %}" alt="profile card">
    </div>

    <div class="profile-card__cnt js-profile-cnt">
      <div class="profile-card__name">Mike Kerr</div>
      <div class="profile-card__txt">Your Request has been Submitted Successfully</div>
      
      <h3>Thank you</h3>
  </div>
</div>
<script  src="{% static 'script.js' %}"></script>

</body>
</html>